<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RN9H6QU" failures="1" tests="4" name="com.api.auto.testcase.TC_API_advance" time="1.089" errors="0" timestamp="2023-07-04T16:51:41 ICT" skipped="0">
  <testcase classname="com.api.auto.testcase.TC_API_advance" name="TC01_Validate200Ok" time="0.019"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_advance" name="TC02_ValidateMessage" time="1.004"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_advance" name="TC03_ValidateToken" time="0.027"/>
  <system-out/>
  <testcase classname="com.api.auto.testcase.TC_API_advance" name="TC04_ValidateUserType" time="0.039">
    <failure message="expected [user field check Failed!] but found [[id:132, name:Test 01, email:testerFunix@funix.edu.vn, account:testerFunix, password:Abc13579, type:UNGVIEN, avatar:http://localhost:5000/public/images/avatar/1673242461173_download.png, phone:0912345678, sex:Nam, birthday:01/01/2000, experience:1 Nam, skill:Java, C++, nation:null, description:LTV, foreiginLanguage:N1, education:ĐH, careerGoals:null, Certificate:http://localhost:5000/public/images/avatar/1673242461173_download.png, createdAt:2023-01-09T05:34:21.000Z, updatedAt:2023-01-09T05:34:21.000Z]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [user field check Failed!] but found [[id:132, name:Test 01, email:testerFunix@funix.edu.vn, account:testerFunix, password:Abc13579, type:UNGVIEN, avatar:http://localhost:5000/public/images/avatar/1673242461173_download.png, phone:0912345678, sex:Nam, birthday:01/01/2000, experience:1 Nam, skill:Java, C++, nation:null, description:LTV, foreiginLanguage:N1, education:ĐH, careerGoals:null, Certificate:http://localhost:5000/public/images/avatar/1673242461173_download.png, createdAt:2023-01-09T05:34:21.000Z, updatedAt:2023-01-09T05:34:21.000Z]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.api.auto.testcase.TC_API_advance.TC04_ValidateUserType(TC_API_advance.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC04_ValidateUserType -->
  <system-out/>
</testsuite> <!-- com.api.auto.testcase.TC_API_advance -->
